apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21-ab-c2-svc1
  namespace: rq21-ab-c2-strict
  labels:
    app: thesis-inference
    experiment: rq21-ab-c2-strict
    workload-role: service-account
    security-condition: mesh_strict_mtls_no_authz
    mesh-enabled: 'true'
    condition: chain_2svc_mesh_strict_mtls_no_authz
    experiment-condition: chain_2svc_mesh_strict_mtls_no_authz
    segment-index: '1'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21-ab-c2-svc2
  namespace: rq21-ab-c2-strict
  labels:
    app: thesis-inference
    experiment: rq21-ab-c2-strict
    workload-role: service-account
    security-condition: mesh_strict_mtls_no_authz
    mesh-enabled: 'true'
    condition: chain_2svc_mesh_strict_mtls_no_authz
    experiment-condition: chain_2svc_mesh_strict_mtls_no_authz
    segment-index: '2'
