apiVersion: v1
kind: Pod
metadata:
  name: rq21-ms-direct-20260516100127
  namespace: rq21-ms-l2-plain-client
  labels:
    app: thesis-inference
    condition: chain_2svc_split_l2_plain
    experiment-condition: chain_2svc_split_l2_plain
    workload-role: debug-client
    role: debug-client
    mesh-enabled: 'false'
    security-condition: plain
  annotations:
    sidecar.istio.io/inject: 'false'
spec:
  restartPolicy: Never
  containers:
  - name: debug
    image: thesisrq15acr.azurecr.io/thesis-inference@sha256:d292aef407ee8a15da2bdaa680de1cc24b0975e7de81d27e1fc3a7d128b8736b
    imagePullPolicy: Always
    command:
    - sleep
    - infinity
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: '1'
        memory: 1Gi
  nodeSelector:
    agentpool: rq15pool
    workload: benchmark
  tolerations:
  - key: workload
    operator: Equal
    value: benchmark
    effect: NoSchedule
