apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21b-chain2-svc1
  namespace: rq21b-chain2-mtls
  labels:
    app: thesis-inference
    experiment: rq21b-chain2-mtls
    workload-role: service-account
    security-condition: mtls
    mesh-enabled: 'true'
    condition: chain_2svc_mtls_multinode
    experiment-condition: chain_2svc_mtls_multinode
    segment-index: '1'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21b-chain2-svc2
  namespace: rq21b-chain2-mtls
  labels:
    app: thesis-inference
    experiment: rq21b-chain2-mtls
    workload-role: service-account
    security-condition: mtls
    mesh-enabled: 'true'
    condition: chain_2svc_mtls_multinode
    experiment-condition: chain_2svc_mtls_multinode
    segment-index: '2'
