# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"2\n\x0cInferRequest\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\"u\n\rInferResponse\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\x16\n\x0e\x64\x65serialize_ms\x18\x03 \x01(\x01\x12\x12\n\ncompute_ms\x18\x04 \x01(\x01\x12\x14\n\x0cserialize_ms\x18\x05 \x01(\x01\x32N\n\x10InferenceService\x12:\n\x05Infer\x12\x17.inference.InferRequest\x1a\x18.inference.InferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERREQUEST']._serialized_start=30
  _globals['_INFERREQUEST']._serialized_end=80
  _globals['_INFERRESPONSE']._serialized_start=82
  _globals['_INFERRESPONSE']._serialized_end=199
  _globals['_INFERENCESERVICE']._serialized_start=201
  _globals['_INFERENCESERVICE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
