apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21-chain5-svc1
  namespace: rq21-chain5-mtls
  labels:
    app: thesis-inference
    experiment: rq21-chain5-mtls
    workload-role: service-account
    security-condition: mtls
    mesh-enabled: 'true'
    condition: chain_5svc_mtls
    experiment-condition: chain_5svc_mtls
    segment-index: '1'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21-chain5-svc2
  namespace: rq21-chain5-mtls
  labels:
    app: thesis-inference
    experiment: rq21-chain5-mtls
    workload-role: service-account
    security-condition: mtls
    mesh-enabled: 'true'
    condition: chain_5svc_mtls
    experiment-condition: chain_5svc_mtls
    segment-index: '2'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21-chain5-svc3
  namespace: rq21-chain5-mtls
  labels:
    app: thesis-inference
    experiment: rq21-chain5-mtls
    workload-role: service-account
    security-condition: mtls
    mesh-enabled: 'true'
    condition: chain_5svc_mtls
    experiment-condition: chain_5svc_mtls
    segment-index: '3'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21-chain5-svc4
  namespace: rq21-chain5-mtls
  labels:
    app: thesis-inference
    experiment: rq21-chain5-mtls
    workload-role: service-account
    security-condition: mtls
    mesh-enabled: 'true'
    condition: chain_5svc_mtls
    experiment-condition: chain_5svc_mtls
    segment-index: '4'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rq21-chain5-svc5
  namespace: rq21-chain5-mtls
  labels:
    app: thesis-inference
    experiment: rq21-chain5-mtls
    workload-role: service-account
    security-condition: mtls
    mesh-enabled: 'true'
    condition: chain_5svc_mtls
    experiment-condition: chain_5svc_mtls
    segment-index: '5'
