apiVersion: v1
kind: Namespace
metadata:
  name: rq21-ab-c0-plain
  labels:
    experiment: rq21-ab-c0-plain
    workload-role: inference
    security-condition: plain_nonmesh
    mesh-enabled: 'false'
---
apiVersion: v1
kind: Namespace
metadata:
  name: rq21-ab-c0-client
  labels:
    experiment: rq21-ab-c0-plain
    workload-role: benchmark-client
    security-condition: plain_nonmesh
    mesh-enabled: 'false'
